### ISSUE TITLE
where do i add enable password on this script 

### ISSUE THREAD

**Issue by Aj46in** [alypher/script-to-backup-dell-switches#1]
Hi Alypher ,

can you suggest where do we add the line for enable password

**Comment by alypher** [comment]
Hey, 

We have two different scripts, the basic one is https://github.com/alypher/script-to-backup-dell-switches/blob/main/script.py, that was planned to have the same password to login and to enable the admin role, and we have the other that we can add some attributes (password, enable password and so on) to a specific host, that here you can put different passwords for both, to ssh, and another to enable de admin. 
The enable password should be configured into hosts list, following the structure: (ip, ssh username, ssh password, enable password, host name)

https://github.com/alypher/script-to-backup-dell-switches/blob/main/script-with-attrs.py

**Comment by Aj46in** [comment]
tested all working Thanks Mate,

out of curiosity, how can I get the hostname of a switch as a filename on output?

**Comment by alypher** [comment]
You should update this line:

remote_conn.send("copy running-config tftp://"+tftp_server+"/"+getattr(host, 'name')+"-"+st+".txt\n")

After the “/“, you should inform the name of the file, in this example, we are using the name and the date time to compose, separated by “-“, but you can change it as you want

**Comment by Aj46in** [comment]
i got this error

File "C:\python\newscript.py", line 35, in do_backup_to_tftp
    remote_conn.send("copy running-config tftp://"+tftp_server+"/"+getattr(host, 'name')+"-"+st+"\n")
                                                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'

**Comment by alypher** [comment]
Did you fill the host information at the first lines?

Like this:
Host('10.8.0.101', 'admin', 'pass1', 'pass1!', 'sw-1'),

The last parameter is the name that you are referring

**Comment by Aj46in** [comment]
No i trying here is get the hostname from the switch and update that hostname on the output file that's saved to tftp location. 

do we can add another line that can send command and get the hostname.
